version: "3"

env:
  GOBIN: "{{ .ROOT_DIR }}/bin"
  PATH: "{{ .GOBIN }}:{{ .PATH }}"

tasks:
  install-binary:
    cmds:
      - go install {{ .DEP_MODULE }}@{{ .DEP_VERSION }}
    status:
      - test -d {{ .GOBIN }}
      - test -f {{ .GOBIN }}/{{ base .DEP_MODULE }}
    internal: true

  binaries:
    deps:
      - task: install-binary
        vars:
          DEP_VERSION: v1.50.0
          DEP_MODULE: github.com/golangci/golangci-lint/cmd/golangci-lint

      - task: install-binary
        vars:
          DEP_VERSION: latest
          DEP_MODULE: golang.org/x/tools/cmd/goimports

  lint:
    deps: [binaries]
    cmds:
      - golangci-lint run {{ .ROOT_DIR }}/...

  imports:
    deps: [binaries]
    cmds:
      - goimports -w {{ .ROOT_DIR }}

  build:
    cmds:
      - go build -o {{ .GOBIN }}/fts -tags fts5

  tidy:
    cmds:
      - go mod tidy

  precommit:
    cmds:
      - task: tidy
      - task: imports
      - task: lint
      - task: build